# Generated by Django 4.2.7 on 2025-09-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='error_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='LibraryLocationMaster',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_librarylocationmaster',
            },
        ),
        migrations.CreateModel(
            name='WardMaster',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.TextField(blank=True, null=True)),
                ('ward_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('accounting_code', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_wardmaster',
            },
        ),
        migrations.CreateModel(
            name='tbl_librarymasterL01',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('library_code', models.TextField(blank=True, null=True)),
                ('library_name', models.TextField(blank=True, null=True)),
                ('landing_page_link', models.TextField(blank=True, null=True)),
                ('about_library', models.TextField(blank=True, null=True)),
                ('library_rules', models.TextField(blank=True, null=True)),
                ('membership_rules', models.TextField(blank=True, null=True)),
                ('membership_page_link', models.TextField(blank=True, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('location_url', models.TextField(blank=True, null=True)),
                ('librarian_name', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('instagram_url', models.TextField(blank=True, null=True)),
                ('youtube_url', models.TextField(blank=True, null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('library_accounting_code', models.ForeignKey(blank=True, db_column='accounting_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_accounting_codeL01', to='L01.wardmaster')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librariesL01', to='L01.librarylocationmaster')),
                ('parent_ward', models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_librariesL01', to='L01.wardmaster')),
            ],
            options={
                'db_table': 'tbl_librarymasterL01',
            },
        ),
        migrations.AddField(
            model_name='librarylocationmaster',
            name='ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='L01.wardmaster'),
        ),
    ]
