# Generated by Django 4.2.7 on 2025-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('membership_type', models.TextField(blank=True, null=True)),
                ('membership_type_en', models.TextField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outsider', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days', models.IntegerField(default=0)),
                ('item', models.IntegerField(default=0)),
                ('remarks_txt', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_membershipmaster',
            },
        ),
    ]
