# Generated by Django 4.2.7 on 2025-09-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0002_membershipmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=500)),
                ('document_name_mar', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_documentmaster',
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=50, unique=True)),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_statusmaster',
            },
        ),
        migrations.CreateModel(
            name='MembershipDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('ward', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('library_name', models.TextField(blank=True, null=True)),
                ('local_address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('office_phone', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('institute_name', models.TextField(blank=True, null=True)),
                ('recommender_details', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('membership', models.ForeignKey(db_column='membership_id', on_delete=django.db.models.deletion.CASCADE, related_name='membership_holders', to='L01.membershipmaster')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='L01.statusmaster')),
            ],
            options={
                'db_table': 'tbl_membershipdetails',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_usages', to='L01.documentmaster')),
                ('membership', models.ForeignKey(db_column='membership_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='L01.membershipdetails')),
            ],
            options={
                'db_table': 'tbl_documentdetails',
            },
        ),
    ]
