# Generated by Django 4.2.7 on 2025-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0003_documentmaster_statusmaster_membershipdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_librarymasterl01',
            name='est_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_librarymasterl01',
            name='library_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
