# Generated by Django 4.2.7 on 2025-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0004_tbl_librarymasterl01_est_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='library_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
