# Generated by Django 4.2.7 on 2025-09-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0005_membershipdetails_library_name_mar'),
    ]

    operations = [
        migrations.CreateModel(
            name='parameter_master',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.TextField(blank=True, null=True)),
                ('parameter_value', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'parameter_master',
            },
        ),
    ]
