# Generated by Django 4.2.7 on 2025-09-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0006_parameter_master'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parameter_master',
            table='parameter_master_L01',
        ),
    ]
