# Generated by Django 4.2.7 on 2025-09-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0007_alter_parameter_master_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parameter_master',
            new_name='parameter_master_L01',
        ),
    ]
