# Generated by Django 4.2.7 on 2025-09-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0008_rename_parameter_master_parameter_master_l01'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetails',
            name='file_name',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='address_same_as_aadhar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='deposit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='entry_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='is_resident_of_nmmc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='member_type',
            field=models.ForeignKey(blank=True, db_column='member_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_types', to='L01.parameter_master_l01'),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='membership_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='subscription',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentdetails',
            name='file_path',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
