# Generated by Django 4.2.7 on 2025-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0009_documentdetails_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='first_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='last_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='middle_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
