# Generated by Django 4.2.7 on 2025-09-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0010_membershipdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipdetails',
            name='membership',
            field=models.ForeignKey(db_column='membershipmaster_id', on_delete=django.db.models.deletion.CASCADE, related_name='membership_holders', to='L01.membershipmaster'),
        ),
    ]
