# Generated by Django 4.2.7 on 2025-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0011_alter_membershipdetails_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='actionperformed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='reviewed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
