# Generated by Django 4.2.7 on 2025-09-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0012_membershipdetails_actionperformed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incrementFieldName', models.CharField(max_length=50, unique=True)),
                ('incrementFieldNumber', models.TextField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_incrementmaster',
            },
        ),
    ]
