# Generated by Django 4.2.7 on 2025-09-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0013_incrementmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='membership_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
