# Generated by Django 4.2.7 on 2025-09-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0014_membershipdetails_membership_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit_amount', models.FloatField(blank=True, null=True)),
                ('entry_fee_amount', models.FloatField(blank=True, null=True)),
                ('monthly_subscription_amount', models.FloatField(blank=True, null=True)),
                ('total_subscription_amount', models.FloatField(blank=True, null=True)),
                ('subscription_from', models.DateField(blank=True, null=True)),
                ('subscription_to', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('membership_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('membership', models.ForeignKey(db_column='membership_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='L01.membershipdetails')),
                ('status', models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_statuses', to='L01.statusmaster')),
            ],
            options={
                'db_table': 'tbl_paymentdetails',
            },
        ),
    ]
