# Generated by Django 4.2.7 on 2025-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0015_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
