# Generated by Django 4.2.7 on 2025-09-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0016_paymentdetails_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDetailsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('first_name_mar', models.TextField(blank=True, null=True)),
                ('middle_name_mar', models.TextField(blank=True, null=True)),
                ('last_name_mar', models.TextField(blank=True, null=True)),
                ('ward', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('library_name', models.TextField(blank=True, null=True)),
                ('library_name_mar', models.TextField(blank=True, null=True)),
                ('local_address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('office_phone', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('institute_name', models.TextField(blank=True, null=True)),
                ('recommender_details', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('membership_duration', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('entry_fees', models.FloatField(blank=True, null=True)),
                ('subscription', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_resident_of_nmmc', models.IntegerField(default=0)),
                ('address_same_as_aadhar', models.IntegerField(default=0)),
                ('actionperformed', models.TextField(blank=True, null=True)),
                ('reviewed', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('membership_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('member_type', models.ForeignKey(blank=True, db_column='member_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_types_history', to='L01.parameter_master_l01')),
                ('membership', models.ForeignKey(db_column='membershipdetails_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='L01.membershipdetails')),
                ('membershipmaster', models.ForeignKey(blank=True, db_column='membershipmaster_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_holders_history', to='L01.membershipmaster')),
                ('status', models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_history', to='L01.statusmaster')),
            ],
            options={
                'db_table': 'tbl_membershipdetails_history',
            },
        ),
    ]
