# Generated by Django 4.2.7 on 2025-10-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0017_membershipdetailshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetailsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=555)),
                ('file_path', models.CharField(max_length=555)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_history', to='L01.documentmaster')),
                ('membership', models.ForeignKey(db_column='membership_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_history', to='L01.membershipdetails')),
                ('original_document', models.ForeignKey(blank=True, db_column='documentdetails_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_versions', to='L01.documentdetails')),
            ],
            options={
                'db_table': 'tbl_documentdetails_history',
            },
        ),
    ]
