# Generated by Django 4.2.7 on 2025-10-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_bookcatalog_front_page_photo_and_more'),
        ('L01', '0018_documentdetailshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationCopyStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_processed', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('accession', models.ForeignKey(blank=True, db_column='accession_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accession_status', to='Masters.bookaccession')),
                ('bookcatalog', models.ForeignKey(blank=True, db_column='bookcatalog_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookcatalog_status', to='Masters.bookcatalog')),
                ('current_status', models.ForeignKey(blank=True, db_column='current_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status', to='Masters.status_master')),
                ('processing_status', models.ForeignKey(blank=True, db_column='processing_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_status', to='Masters.status_master')),
                ('shelf_location', models.ForeignKey(blank=True, db_column='shelf_location_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_location_status', to='Masters.resourcelocationmaster')),
            ],
            options={
                'db_table': 'tbl_circulation',
            },
        ),
    ]
