# Generated by Django 4.2.7 on 2025-10-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0019_circulationcopystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationcopystatus',
            name='accession_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
