# Generated by Django 4.2.7 on 2025-10-16 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_bookcatalog_front_page_photo_and_more'),
        ('L01', '0020_circulationcopystatus_accession_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fine_status', models.CharField(blank=True, max_length=20, null=True)),
                ('fine_paid_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=20, null=True)),
                ('issued_by', models.TextField(blank=True, null=True)),
                ('received_by', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('accession', models.ForeignKey(db_column='accession_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Masters.bookaccession')),
                ('catalog', models.ForeignKey(blank=True, db_column='cat_ref_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Masters.bookcatalog')),
                ('circulation', models.ForeignKey(blank=True, db_column='copy_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='L01.circulationcopystatus')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='L01.membershipdetails')),
                ('return_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_with_condition', to='Masters.status_master')),
            ],
            options={
                'db_table': 'tbl_circulation_transaction',
            },
        ),
    ]
