# Generated by Django 4.2.7 on 2025-10-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0021_circulationtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationtransaction',
            name='membership_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
