# Generated by Django 4.2.7 on 2025-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0022_circulationtransaction_membership_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulationtransaction',
            old_name='renewal_count',
            new_name='days_overdue_count',
        ),
        migrations.AddField(
            model_name='circulationtransaction',
            name='book_fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='circulationtransaction',
            name='total_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
