# Generated by Django 4.2.7 on 2025-10-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0023_rename_renewal_count_circulationtransaction_days_overdue_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='circulation_transaction',
            field=models.ForeignKey(blank=True, db_column='circulation_transaction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='L01.circulationtransaction'),
        ),
    ]
