# Generated by Django 4.2.7 on 2025-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0024_paymentdetails_circulation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='book_fine_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='fine_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
