# Generated by Django 4.2.7 on 2025-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0025_paymentdetails_book_fine_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('receipt_no', models.CharField(blank=True, max_length=500, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_upload', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_payment_report',
            },
        ),
    ]
