# Generated by Django 4.2.7 on 2025-10-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0026_paymentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReportKeyValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_report', models.ForeignKey(db_column='payment_report_id', on_delete=django.db.models.deletion.CASCADE, related_name='key_values', to='L01.paymentreport')),
            ],
            options={
                'db_table': 'tbl_payment_report_keyvalue',
            },
        ),
    ]
