# Generated by Django 4.2.7 on 2025-11-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0027_paymentreportkeyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreport',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
