# Generated by Django 4.2.7 on 2025-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0028_paymentreport_deposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreport',
            name='generated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
