# Generated by Django 4.2.7 on 2025-11-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0029_alter_paymentreport_generated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='membership_renew',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='membership_renew',
            field=models.IntegerField(default=0),
        ),
    ]
