# Generated by Django 4.2.7 on 2025-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0030_membershipdetails_membership_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
