# Generated by Django 5.2.5 on 2025-11-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0031_membershipdetails_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveExamMaster',
            fields=[
                ('competitive_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('short_form', models.CharField(blank=True, max_length=50, null=True)),
                ('competitive_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_competitive_exam_master',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('section_name', models.TextField(blank=True, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('competitive_id', models.ForeignKey(db_column='competitive_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='L01.competitiveexammaster')),
            ],
            options={
                'db_table': 'tbl_sections',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.TextField(blank=True, null=True)),
                ('subject_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('section_no', models.ForeignKey(db_column='section_no', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='L01.sections')),
            ],
            options={
                'db_table': 'tbl_subjects',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.TextField(blank=True, null=True)),
                ('topic_reference', models.TextField(blank=True, null=True)),
                ('topic_image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_id', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='L01.subjects')),
            ],
            options={
                'db_table': 'tbl_topics',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('chapter_name', models.TextField(blank=True, null=True)),
                ('chapter_pdf_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('topic_id', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='L01.topics')),
            ],
            options={
                'db_table': 'tbl_chapters',
            },
        ),
    ]
