# Generated by Django 4.2.7 on 2025-11-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0031_membershipdetails_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='other_ward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='other_ward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
