# Generated by Django 5.2.5 on 2025-11-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0032_competitiveexammaster_sections_subjects_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='section_no',
            field=models.ForeignKey(blank=True, db_column='section_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='L01.sections'),
        ),
        migrations.AddField(
            model_name='topics',
            name='section_no',
            field=models.ForeignKey(blank=True, db_column='section_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='L01.sections'),
        ),
    ]
