# Generated by Django 5.0.9 on 2025-11-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0033_memberentryexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookTypeMaster',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('ebookTypeCode', models.TextField(blank=True, null=True)),
                ('ebookTypeNameEnglish', models.TextField(blank=True, null=True)),
                ('ebookTypeNameMarathi', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_ebooktypemaster',
            },
        ),
    ]
