# Generated by Django 5.0.9 on 2025-11-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0034_ebooktypemaster'),
        ('Masters', '0025_bookcatalog_front_page_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEbook',
            fields=[
                ('ebook_id', models.AutoField(primary_key=True, serialize=False)),
                ('eb_title', models.TextField(blank=True, null=True)),
                ('eb_subtitle', models.TextField(blank=True, null=True)),
                ('eb_author', models.TextField(blank=True, null=True)),
                ('eb_publisher', models.TextField(blank=True, null=True)),
                ('eb_isbn_issn', models.TextField(blank=True, null=True)),
                ('eb_edition', models.TextField(blank=True, null=True)),
                ('call_number', models.TextField(blank=True, null=True)),
                ('cutter_number', models.TextField(blank=True, null=True)),
                ('e_publication_year', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('eb_keywords', models.TextField(blank=True, null=True)),
                ('eb_language', models.TextField(blank=True, null=True)),
                ('eb_publication_place', models.TextField(blank=True, null=True)),
                ('eb_year_of_publication', models.IntegerField(blank=True, null=True)),
                ('eb_classification_number', models.TextField(blank=True, null=True)),
                ('eb_pages', models.TextField(blank=True, null=True)),
                ('eb_date_of_registration', models.DateField(blank=True, null=True)),
                ('eb_other_authors', models.TextField(blank=True, null=True)),
                ('eb_front_page_photo', models.TextField(blank=True, null=True)),
                ('eb_last_page_photo', models.TextField(blank=True, null=True)),
                ('eb_status_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('eb_subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.subjecttypemaster')),
                ('ebook_type', models.ForeignKey(blank=True, db_column='ebook_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='L01.ebooktypemaster')),
            ],
            options={
                'db_table': 'tbl_library_ebooks',
            },
        ),
    ]
