# Generated by Django 5.0.9 on 2025-11-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0035_libraryebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryebook',
            name='eb_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
