# Generated by Django 4.2.7 on 2025-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0036_libraryebook_eb_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationtransaction',
            name='adjusted_fine',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
