# Generated by Django 4.2.7 on 2025-12-03 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0026_bookcatalog_ebook_bookcatalog_ebook_available'),
        ('L01', '0038_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_code', models.CharField(blank=True, max_length=50, null=True)),
                ('book', models.ForeignKey(blank=True, db_column='cat_ref_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_ref_id_reviews', to='Masters.bookcatalog')),
            ],
            options={
                'db_table': 'tbl_book_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
