# Generated by Django 4.2.7 on 2025-12-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0039_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_book_master',
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_link', models.URLField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='L01.bookmaster')),
            ],
            options={
                'db_table': 'tbl_book_detail',
            },
        ),
    ]
