# Generated by Django 4.2.7 on 2025-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0040_bookmaster_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='preview_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
