# Generated by Django 4.2.7 on 2025-12-08 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0041_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockYearMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_stock_year',
            },
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('stock_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.stockyearmaster')),
            ],
            options={
                'db_table': 'tbl_stock_master',
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('circulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.circulationcopystatus')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.stockmaster')),
                ('stock_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.stockyearmaster')),
            ],
            options={
                'db_table': 'tbl_stock_detail',
            },
        ),
    ]
