# Generated by Django 4.2.7 on 2025-12-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0026_bookcatalog_ebook_bookcatalog_ebook_available'),
        ('L01', '0042_stockyearmaster_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('current_status', models.TextField()),
                ('stock_status', models.TextField()),
                ('date_processed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('shelf_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.resourcelocationmaster')),
                ('stock_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.stockyearmaster')),
            ],
            options={
                'db_table': 'tbl_stock_report',
            },
        ),
    ]
