# Generated by Django 4.2.7 on 2025-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0043_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_title', models.CharField(max_length=255)),
                ('video_path', models.TextField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('campaign_date_from', models.DateField(blank=True, null=True)),
                ('campaign_date_to', models.DateField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_advertisements',
            },
        ),
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('event_from_date', models.DateField(blank=True, null=True)),
                ('event_to_date', models.DateField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_eventannouncements',
            },
        ),
    ]
