# Generated by Django 4.2.7 on 2025-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0044_advertisement_eventannouncement_and_more'),
    ]

    operations = [
        
    ]
