# Generated by Django 4.2.7 on 2025-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0045_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        
        
    ]
