# Generated by Django 4.2.7 on 2025-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0046_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryebook',
            name='cat_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
