# Generated by Django 4.2.7 on 2025-12-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0047_libraryebook_cat_id_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_member_login_session',
            },
        ),
        migrations.CreateModel(
            name='MemberScreenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=100)),
                ('screen_route', models.CharField(max_length=200)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.memberloginsession')),
            ],
            options={
                'db_table': 'tbl_member_activity',
            },
        ),
        migrations.AddField(
            model_name='memberloginsession',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='L01.membershipdetails'),
        ),
    ]
