# Generated by Django 4.2.7 on 2025-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0048_memberloginsession_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmaster',
            name='fine_membership',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
