# Generated by Django 4.2.7 on 2025-12-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0049_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
