# Generated by Django 4.2.7 on 2025-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0050_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='fine_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='gap_fine',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='gap_months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='total_fine_membership',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='fine_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='gap_fine',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='gap_months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='total_fine_membership',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
