# Generated by Django 4.2.7 on 2025-12-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0051_membershipdetails_fine_calculated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRenewalStaging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_from_date', models.DateField(blank=True, null=True)),
                ('old_to_date', models.DateField(blank=True, null=True)),
                ('old_duration', models.IntegerField(blank=True, null=True)),
                ('old_deposit', models.FloatField(blank=True, null=True)),
                ('old_entry_fees', models.FloatField(blank=True, null=True)),
                ('old_subscription', models.FloatField(blank=True, null=True)),
                ('old_membership_id', models.IntegerField(blank=True, null=True)),
                ('new_from_date', models.DateField(blank=True, null=True)),
                ('new_to_date', models.DateField(blank=True, null=True)),
                ('new_duration', models.IntegerField(blank=True, null=True)),
                ('new_deposit', models.FloatField(blank=True, null=True)),
                ('new_entry_fees', models.FloatField(blank=True, null=True)),
                ('new_subscription', models.FloatField(blank=True, null=True)),
                ('new_membership_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_requests', to='L01.membershipdetails')),
            ],
            options={
                'db_table': 'tbl_membership_renewal_staging',
                'ordering': ['-created_at'],
            },
        ),
    ]
