# Generated by Django 4.2.7 on 2025-12-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0052_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='adjusted_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
