# Generated by Django 4.2.7 on 2026-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0053_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
