# Generated by Django 4.2.7 on 2026-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0054_membershipdetails_membership_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='gap_period_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetails',
            name='gap_period_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
