# Generated by Django 4.2.7 on 2026-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0055_membershipdetails_gap_period_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='gap_subscription_delay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
