# Generated by Django 4.2.7 on 2026-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0056_membershipdetails_gap_subscription_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='gap_period_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='gap_period_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='gap_subscription_delay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
