# Generated by Django 4.2.7 on 2026-01-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0057_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBookMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_google_book_master',
            },
        ),
        migrations.CreateModel(
            name='LOCBookMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_loc_book_master',
            },
        ),
        migrations.CreateModel(
            name='LOCBookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_details', to='L01.locbookmaster')),
            ],
            options={
                'db_table': 'tbl_loc_book_detail',
            },
        ),
        migrations.CreateModel(
            name='GoogleBookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_details', to='L01.googlebookmaster')),
            ],
            options={
                'db_table': 'tbl_google_book_detail',
            },
        ),
    ]
