# Generated by Django 6.0.1 on 2026-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0058_googlebookmaster_locbookmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetails',
            name='other_ward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipdetailshistory',
            name='other_ward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
