# Generated by Django 6.0.1 on 2026-01-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0059_membershipdetails_other_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberentryexit',
            name='member',
            field=models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ember_entry', to='L01.membershipdetails'),
        ),
    ]
