# Generated by Django 6.0.1 on 2026-04-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0060_memberentryexit_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationtransaction',
            name='book_extended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circulationtransaction',
            name='extended_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
