# Generated by Django 6.0.1 on 2026-04-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0061_circulationtransaction_book_extended_and_more')
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationTransactionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('days_overdue_count', models.IntegerField(default=0)),
                ('book_fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_fine', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fine_status', models.CharField(blank=True, max_length=20, null=True)),
                ('fine_paid_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=20, null=True)),
                ('book_extended', models.IntegerField(default=0)),
                ('extended_on', models.DateField(blank=True, null=True)),
                ('issued_by', models.TextField(blank=True, null=True)),
                ('received_by', models.TextField(blank=True, null=True)),
                ('membership_code', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('EXTEND', 'Extend'), ('RETURN', 'Return'), ('DELETE', 'Delete')], default='UPDATE', max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('accession', models.ForeignKey(db_column='accession_id', on_delete=django.db.models.deletion.CASCADE, related_name='history_transactions', to='Masters.bookaccession')),
                ('catalog', models.ForeignKey(blank=True, db_column='cat_ref_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_transactions', to='Masters.bookcatalog')),
                ('circulation', models.ForeignKey(blank=True, db_column='copy_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_transactions', to='L01.circulationcopystatus')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='history_transactions', to='L01.membershipdetails')),
                ('original_transaction', models.ForeignKey(db_column='original_transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='L01.circulationtransaction')),
                ('return_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_transactions', to='Masters.status_master')),
            ],
            options={
                'db_table': 'tbl_circulation_transaction_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['original_transaction', '-created_at'], name='tbl_circula_origina_d86b87_idx'), models.Index(fields=['barcode', '-created_at'], name='tbl_circula_barcode_3e5285_idx'), models.Index(fields=['member', '-created_at'], name='tbl_circula_member__ea38f0_idx')],
            },
        ),
    ]
