# Generated by Django 6.0.1 on 2026-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0062_circulationtransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipdetails',
            name='aadhar_no',
            field=models.CharField(max_length=12),
        ),
    ]
