# Generated by Django 5.0.9 on 2025-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='form_view',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='report_view',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='workflow_view',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='govt_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_proof',
            field=models.FileField(blank=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('account', 'Accounts'), ('student', 'Student/Member'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
