# Generated by Django 4.2.7 on 2025-09-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTPText', models.TextField()),
                ('OTPPurpose', models.CharField(max_length=255)),
                ('OTPIDNumber', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'otp_messages',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('unique_id', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('response_status', models.CharField(blank=True, max_length=50)),
                ('response_uri', models.CharField(blank=True, max_length=255)),
                ('status_description', models.TextField(blank=True)),
                ('error_exception', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('library_code', models.TextField(blank=True, null=True)),
                ('membership_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sms_log',
            },
        ),
    ]
