# Generated by Django 4.2.7 on 2025-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_otpmessage_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
