# Generated by Django 6.0.1 on 2026-01-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_otplog_verifyotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyotp',
            name='otp_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_log_verify', to='Account.otplog'),
        ),
    ]
