# Generated by Django 4.2.23 on 2026-01-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_verifyotp_otp_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
