# Generated by Django 4.2.7 on 2025-09-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymaster',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='library_rules',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='library_type',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='membership_rules',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='librarymaster',
            name='social_links',
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='establishedYear',
            field=models.TextField(blank=True, null=True),
        ),
    ]
