# Generated by Django 4.2.7 on 2025-09-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_wardmaster_librarylocationmaster'),
        ('administration', '0002_remove_librarymaster_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymaster',
            name='library_accounting_code',
            field=models.ForeignKey(blank=True, db_column='accounting_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_accounting_code', to='Masters.wardmaster'),
        ),
        migrations.AlterField(
            model_name='librarymaster',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libraries', to='Masters.librarylocationmaster'),
        ),
        migrations.AlterField(
            model_name='librarymaster',
            name='parent_ward',
            field=models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_libraries', to='Masters.wardmaster'),
        ),
    ]
