# Generated by Django 4.2.7 on 2025-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_librarymaster_library_accounting_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymaster',
            name='establishedYear',
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='contact_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='contact_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='instagram_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='librarian_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='library_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='location_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='membership_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='twitter_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
