# Generated by Django 4.2.7 on 2025-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_librarymaster_establishedyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymaster',
            name='est_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarymaster',
            name='library_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
