# Generated by Django 4.2.7 on 2025-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTypeMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subjectNameEnglish', models.TextField(blank=True, null=True)),
                ('subjectNameMarathi', models.TextField(blank=True, null=True)),
                ('subjectDescription', models.TextField(blank=True, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_subjectTypeMaster',
            },
        ),
    ]
