# Generated by Django 4.2.7 on 2025-08-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_subjecttypemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCatalog',
            fields=[
                ('cat_ref_num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('isbn_issn', models.TextField(blank=True, null=True)),
                ('edition', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('publication_place', models.TextField(blank=True, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('classification_number', models.TextField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.subjecttypemaster')),
            ],
            options={
                'db_table': 'tbl_bookCatalog',
            },
        ),
        migrations.CreateModel(
            name='BookAccession',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('copies', models.TextField(blank=True, null=True)),
                ('accession_number_from', models.TextField(blank=True, null=True)),
                ('accession_number_to', models.TextField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.TextField(blank=True, default='INR', null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('catalog_ref_no', models.ForeignKey(blank=True, db_column='catalog_ref_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.bookcatalog')),
            ],
            options={
                'db_table': 'tbl_bookAccession',
            },
        ),
    ]
