# Generated by Django 4.2.7 on 2025-08-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_bookcatalog_bookaccession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcatalog',
            name='pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
