# Generated by Django 4.2.7 on 2025-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_alter_bookcatalog_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccession',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookaccession',
            name='discount_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookaccession',
            name='discount_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookaccession',
            name='tax_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookaccession',
            name='tax_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookaccession',
            name='total_cost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookaccession',
            name='unit_price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
