# Generated by Django 4.2.7 on 2025-08-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_alter_bookaccession_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBookCatalog',
            fields=[
                ('cat_ref_num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('isbn_issn', models.TextField(blank=True, null=True)),
                ('edition', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('publication_place', models.TextField(blank=True, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('classification_number', models.TextField(blank=True, null=True)),
                ('pages', models.TextField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.subjecttypemaster')),
            ],
            options={
                'db_table': 'tbl_TestbookCatalog',
            },
        ),
    ]
