# Generated by Django 4.2.7 on 2025-09-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_testbookcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.TextField(blank=True, null=True)),
                ('language_name', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_languageMaster',
            },
        ),
    ]
