# Generated by Django 4.2.7 on 2025-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_languagemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttypemaster',
            name='is_Active',
        ),
        migrations.AddField(
            model_name='subjecttypemaster',
            name='subjectCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjecttypemaster',
            name='is_active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
