# Generated by Django 4.2.7 on 2025-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_remove_subjecttypemaster_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaTypeMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('materialCode', models.TextField(blank=True, null=True)),
                ('materialNameEnglish', models.TextField(blank=True, null=True)),
                ('materialNameMarathi', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_materiaTypeMaster',
            },
        ),
    ]
