# Generated by Django 4.2.7 on 2025-09-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_materiatypemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalog',
            name='call_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='cutter_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='material_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='publication_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
