# Generated by Django 4.2.7 on 2025-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_bookcatalog_call_number_bookcatalog_cutter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalog',
            name='other_authors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
