# Generated by Django 4.2.7 on 2025-09-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_bookcatalog_other_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMaster',
            fields=[
                ('author_code', models.AutoField(primary_key=True, serialize=False)),
                ('author_short_name', models.TextField(blank=True, null=True)),
                ('author_name_english', models.TextField(blank=True, null=True)),
                ('author_name_other_english', models.TextField(blank=True, null=True)),
                ('author_name_marathi', models.TextField(blank=True, null=True)),
                ('author_name_other_marathi', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_authormaster',
            },
        ),
    ]
