# Generated by Django 4.2.7 on 2025-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0012_authormaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriaTypeMaster',
            new_name='MaterialTypeMaster',
        ),
        migrations.AlterModelTable(
            name='materialtypemaster',
            table='tbl_MaterialTypeMaster',
        ),
    ]
