# Generated by Django 4.2.7 on 2025-09-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0013_rename_materiatypemaster_materialtypemaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcatalog',
            name='material_type',
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='material',
            field=models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.materialtypemaster'),
        ),
    ]
