# Generated by Django 4.2.7 on 2025-09-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0014_remove_bookcatalog_material_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAccession',
        ),
    ]
