# Generated by Django 4.2.7 on 2025-09-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_delete_bookaccession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAccession',
            fields=[
                ('accession_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('supplier_vendor', models.TextField(blank=True, null=True)),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('funding_source', models.TextField(blank=True, null=True)),
                ('condition_at_entry', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('catalogue', models.ForeignKey(blank=True, db_column='catalog_ref_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.bookcatalog')),
            ],
            options={
                'db_table': 'tbl_bookaccession',
            },
        ),
    ]
