# Generated by Django 4.2.7 on 2025-09-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0016_bookaccession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionAtEntryMaster',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_code', models.CharField(max_length=50, unique=True)),
                ('condition_at_entry', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_conditionAtEntryMaster',
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('currency_name', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_currencyMaster',
            },
        ),
        migrations.CreateModel(
            name='FundingSourceMaster',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_code', models.CharField(max_length=50, unique=True)),
                ('funding_source_name', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_fundingSourceMaster',
            },
        ),
        migrations.CreateModel(
            name='ResourceLocationMaster',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_resourceLocationMaster',
            },
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('supplier_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_supplierMaster',
            },
        ),
    ]
