# Generated by Django 4.2.7 on 2025-09-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_conditionatentrymaster_currencymaster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAccession',
        ),
    ]
