# Generated by Django 4.2.7 on 2025-09-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_delete_bookaccession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAccession',
            fields=[
                ('accession_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_number', models.IntegerField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('catalogue', models.ForeignKey(blank=True, db_column='catalog_ref_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.bookcatalog')),
                ('condition_at_entry', models.ForeignKey(blank=True, db_column='condition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.conditionatentrymaster')),
                ('currency', models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.currencymaster')),
                ('funding_source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.fundingsourcemaster')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.resourcelocationmaster')),
                ('status', models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.status_master')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.suppliermaster')),
            ],
            options={
                'db_table': 'tbl_bookaccession',
            },
        ),
    ]
