# Generated by Django 4.2.7 on 2025-09-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0019_bookaccession'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookcatalog',
            table='tbl_bookcatalog',
        ),
        migrations.AlterModelTable(
            name='conditionatentrymaster',
            table='tbl_conditionatentrymaster',
        ),
        migrations.AlterModelTable(
            name='currencymaster',
            table='tbl_currencymaster',
        ),
        migrations.AlterModelTable(
            name='fundingsourcemaster',
            table='tbl_fundingsourcemaster',
        ),
        migrations.AlterModelTable(
            name='languagemaster',
            table='tbl_languagemaster',
        ),
        migrations.AlterModelTable(
            name='materialtypemaster',
            table='tbl_materialtypemaster',
        ),
        migrations.AlterModelTable(
            name='resourcelocationmaster',
            table='tbl_resourcelocationmaster',
        ),
        migrations.AlterModelTable(
            name='subjecttypemaster',
            table='tbl_subjecttypemaster',
        ),
        migrations.AlterModelTable(
            name='suppliermaster',
            table='tbl_suppliermaster',
        ),
        migrations.AlterModelTable(
            name='testbookcatalog',
            table='tbl_Testbookcatalog',
        ),
    ]
