# Generated by Django 4.2.7 on 2025-09-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0020_alter_bookcatalog_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardMaster',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.TextField(blank=True, null=True)),
                ('ward_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('accounting_code', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_wardmaster',
            },
        ),
        migrations.CreateModel(
            name='LibraryLocationMaster',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('ward', models.ForeignKey(blank=True, db_column='ward_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='Masters.wardmaster')),
            ],
            options={
                'db_table': 'tbl_librarylocationmaster',
            },
        ),
    ]
