# Generated by Django 4.2.7 on 2025-09-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_wardmaster_librarylocationmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_search',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='application_search',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='document_master',
        ),
        migrations.RemoveField(
            model_name='parameter_master',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parameter_master',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='application_search',
        ),
        migrations.DeleteModel(
            name='parameter_master',
        ),
    ]
