# Generated by Django 4.2.7 on 2025-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0022_remove_application_search_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookaccession',
            name='accession_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
