# Generated by Django 4.2.7 on 2025-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0023_bookaccession_accession_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccession',
            name='accession_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
