# Generated by Django 4.2.7 on 2025-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0024_alter_bookaccession_accession_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalog',
            name='front_page_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='last_page_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
