# Generated by Django 4.2.7 on 2025-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_bookcatalog_front_page_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardmaster',
            name='ward_name_mar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
