# Generated by Django 5.0.9 on 2025-11-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L01', '0035_libraryebook'),
        ('Masters', '0025_bookcatalog_front_page_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalog',
            name='ebook',
            field=models.ForeignKey(blank=True, db_column='ebook_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='L01.libraryebook'),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='ebook_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
