# Generated by Django 4.2.7 on 2025-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0026_bookcatalog_ebook_bookcatalog_ebook_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormaster',
            name='detail_entered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
