# Generated by Django 4.2.7 on 2025-12-30 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0027_authormaster_detail_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('click_1', models.CharField(blank=True, max_length=255, null=True)),
                ('click_2', models.CharField(blank=True, max_length=255, null=True)),
                ('click_3', models.CharField(blank=True, max_length=255, null=True)),
                ('click_4', models.CharField(blank=True, max_length=255, null=True)),
                ('click_5', models.CharField(blank=True, max_length=255, null=True)),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('popup_shown', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_vsisitor_activity',
            },
        ),
    ]
