# Generated by Django 4.2.7 on 2025-12-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0028_visitoractivity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitoractivity',
            table='tbl_visitor_activity',
        ),
    ]
