# Generated by Django 4.2.7 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0029_alter_visitoractivity_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoractivity',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitoractivity',
            name='visitor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
