# Generated by Django 6.0.1 on 2026-02-06 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0030_visitoractivity_remark_visitoractivity_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalog',
            name='author_fk',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.authormaster'),
        ),
        migrations.AddField(
            model_name='bookcatalog',
            name='author_short_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
