# Generated by Django 4.2.23 on 2026-02-10 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_librarymaster_est_year_and_more'),
        ('Masters', '0031_bookcatalog_author_fk_bookcatalog_author_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('all', 'For All Libraries'), ('specific', 'For Specific Library')], default='all', max_length=20, verbose_name='Event Scope')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('single', 'Single Day Event'), ('multiple', 'Multiple Day Event')], default='single', max_length=20, verbose_name='Event Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('location', models.TextField(verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.librarymaster', verbose_name='Library')),
            ],
            options={
                'verbose_name': 'Library Event',
                'verbose_name_plural': 'Library Events',
            },
        ),
        migrations.CreateModel(
            name='EventPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Event PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='Masters.libraryevent')),
            ],
            options={
                'verbose_name': 'Event PDF',
                'verbose_name_plural': 'Event PDFs',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Event Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Masters.libraryevent')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
            },
        ),
    ]
