# Generated by Django 4.2.23 on 2026-02-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0032_libraryevent_eventpdf_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryevent',
            name='time',
        ),
        migrations.AddField(
            model_name='libraryevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='libraryevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
