# Generated by Django 4.2.23 on 2026-02-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0033_remove_libraryevent_time_libraryevent_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventpdf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='libraryevent',
            options={},
        ),
        migrations.AlterModelTable(
            name='eventimage',
            table='tbl_library_event_image',
        ),
        migrations.AlterModelTable(
            name='eventpdf',
            table='tbl_library_event_pdf',
        ),
        migrations.AlterModelTable(
            name='libraryevent',
            table='tbl_library_event',
        ),
    ]
