# Generated by Django 4.2.23 on 2026-02-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_librarymaster_est_year_and_more'),
        ('Masters', '0034_alter_eventimage_options_alter_eventpdf_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('all', 'For All Libraries'), ('specific', 'For Specific Library')], default='all', max_length=20, verbose_name='Event Scope')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('single', 'Single Day Event'), ('multiple', 'Multiple Day Event')], default='single', max_length=20, verbose_name='Event Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.TextField(verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.librarymaster', verbose_name='Library')),
            ],
            options={
                'db_table': 'tbl_library_events',
            },
        ),
    ]
