# Generated by Django 4.2.23 on 2026-02-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0035_libraryevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryEvents',
        ),
    ]
