# Generated by Django 4.2.23 on 2026-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0036_delete_libraryevents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Event Image', 'verbose_name_plural': 'Event Images'},
        ),
        migrations.AlterModelOptions(
            name='eventpdf',
            options={'verbose_name': 'Event PDF', 'verbose_name_plural': 'Event PDFs'},
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.CharField(max_length=500, verbose_name='Event Image Path'),
        ),
        migrations.AlterField(
            model_name='eventpdf',
            name='pdf_file',
            field=models.CharField(max_length=500, verbose_name='Event PDF Path'),
        ),
    ]
