# Generated by Django 4.2.23 on 2026-02-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0037_alter_eventimage_options_alter_eventpdf_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryevent',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
