# Generated by Django 6.0.1 on 2026-01-21 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('filters_json', models.JSONField(default=dict)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, null=True)),
                ('save_to_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_report_schedule',
            },
        ),
        migrations.CreateModel(
            name='ReportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('member', 'Member Report'), ('book', 'Book Report'), ('financial', 'Financial Report'), ('circulation', 'Circulation Report')], max_length=50)),
                ('filters_json', models.JSONField(default=dict)),
                ('selected_members_json', models.JSONField(default=list)),
                ('tab_filters_json', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_report_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('print', 'Print')], max_length=50)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('filters_applied', models.JSONField(default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('generation_time', models.FloatField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_reports.reportsession')),
            ],
            options={
                'db_table': 'tbl_report_export',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['created_by', 'report_type'], name='tbl_report__created_e9407c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsession',
            index=models.Index(fields=['created_at'], name='tbl_report__created_7b57bf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['exported_by', 'exported_at'], name='tbl_report__exporte_fc4645_idx'),
        ),
    ]
