# Generated by Django 6.0.1 on 2026-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('member', 'Member Report'), ('book', 'Book Report'), ('financial', 'Financial Report'), ('circulation', 'Circulation Report'), ('custom', 'Custom Report')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_model', models.CharField(help_text="Django model path, e.g., 'L01.models.MembershipDetails'", max_length=255)),
                ('tabs', models.JSONField(default=list, help_text='List of tab configurations')),
                ('filters', models.JSONField(default=dict, help_text='Filter configurations')),
                ('columns', models.JSONField(default=list, help_text='Column configurations')),
                ('default_settings', models.JSONField(default=dict, help_text='Default settings for the report')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'db_table': 'tbl_report_configuration',
                'ordering': ['report_type', 'name'],
            },
        ),
    ]
