# Generated by Django 6.0.1 on 2026-01-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportexport',
            name='tbl_report__exporte_fc4645_idx',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='created_by',
        ),
        migrations.RemoveIndex(
            model_name='reportsession',
            name='tbl_report__created_e9407c_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportsession',
            name='tbl_report__created_7b57bf_idx',
        ),
        migrations.RemoveField(
            model_name='reportexport',
            name='exported_by',
        ),
        migrations.RemoveField(
            model_name='reportexport',
            name='session',
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
        migrations.RemoveField(
            model_name='reportsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportsession',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='ReportExport',
        ),
        migrations.DeleteModel(
            name='ReportSession',
        ),
    ]
