"""
Django settings for mantra_io project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
from datetime import timedelta
import socket
from decouple import config
from cryptography.fernet import Fernet

# ✅ ADD THIS - Load .env file
from dotenv import load_dotenv
load_dotenv()  # This loads variables from .env file

# ENCRYPTED_PASSWORD = config("DB_ENCRYPTED_PASSWORD")
# SECRET_KEY = config("DB_SECRET_KEY")

# Decrypt
# fernet = Fernet(SECRET_KEY)
# DECRYPTED_PASSWORD = fernet.decrypt(ENCRYPTED_PASSWORD.encode()).decode()

# ========== ENVIRONMENT DETECTION ==========
def detect_environment():
    """
    Detect environment: local, test, or production
    """
    # 1. Environment variable (ALWAYS wins)
    env_from_var = os.getenv('DJANGO_ENV', '').lower()
    if env_from_var in ['local', 'test', 'production']:
        return env_from_var
    
    # 2. Detect by private IP (for AWS)
    try:
        hostname = socket.gethostname()
        private_ip = socket.gethostbyname(hostname)
        
        print(f"[DEBUG] Hostname: {hostname}")
        print(f"[DEBUG] Private IP: {private_ip}")
        
        # Test Server: 172.26.12.47
        # Production Server: 172.31.44.248
        
        if private_ip == '172.26.13.164':
            return 'test'
        elif private_ip == '172.31.44.248':
            return 'production'
        elif private_ip.startswith('172.26.'):
            return 'test'
        elif private_ip.startswith('172.31.'):
            return 'production'
            
    except Exception as e:
        print(f"[DEBUG] Error detecting IP: {e}")
    
    # 3. Default to local (safest)
    return 'local'

# Set environment
ENVIRONMENT = detect_environment()
print(f"=== Environment detected: {ENVIRONMENT} ===")

# Set DEBUG based on environment
if ENVIRONMENT == 'local':
    DEBUG = True
else:
    DEBUG = False

# # ALLOWED_HOSTS = ['3.111.76.175', '13.203.186.80', '43.205.183.251', 'localhost', '127.0.0.1', 'nmmclibrary.in', '.nmmclibrary.in', 'www.nmmclibrary.in']

# SITE_URL configuration
if ENVIRONMENT == 'local':
    SITE_URL = "http://localhost:8000"
elif ENVIRONMENT == 'test':
    SITE_URL = "http://13.203.186.80"
else:  # production
    SITE_URL = "http://www.nmmclibrary.in"

import mimetypes
mimetypes.add_type("application/javascript", ".mjs")
DATABASE_ROUTERS = ['administration.routers.ServiceRouter']  # Add your router here

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        'ENGINE': 'mysql.connector.django',
        'NAME': 'nlms_db',      # Replace with your database name
        'USER': 'root',      # Replace with your database user
        'PASSWORD': 'Mysql_MH-047319',  # Replace with your database password
        'HOST': '43.205.183.251',       # IP FOR LOCAL VM
        'PORT': '3306',            
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    },
    'L01': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'L01_db',
        'USER': 'root',
        'PASSWORD': 'Mysql_MH-047319',
        'HOST': '43.205.183.251',
        'PORT': '3306',
    },
    'L02': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'L02_db',
        'USER': 'root',
        'PASSWORD': 'Mysql_MH-047319',
        'HOST': '43.205.183.251',
        'PORT': '3306', 
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # safest default
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'lax'
SESSION_COOKIE_SECURE = True  # True only if HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

if ENVIRONMENT == 'production':
    SESSION_COOKIE_DOMAIN = ".nmmclibrary.in"
    CSRF_COOKIE_DOMAIN = ".nmmclibrary.in"
else:
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None

# http://django-crispy-forms.readthedocs.io/en/latest/install.html#template-packs
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ========== MEDIA & FILE STORAGE SETTINGS ==========
if ENVIRONMENT == 'local':
    # For local development (Windows)
    MEDIA_ROOT = os.path.join(BASE_DIR, 'D:/Python Projects/Documents/')
elif ENVIRONMENT == 'test':
    # For test server (Ubuntu)
    MEDIA_ROOT = '/home/ubuntu/Documents/'
else:  # production
    # For production - use AWS S3, so local path is not critical
    MEDIA_ROOT = os.path.join(BASE_DIR, '/tmp/documents/')  # Temporary path

MEDIA_URL = '/media/'

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$vute#e^tqlu5ehd!)vv5m3x!z5^7p%jb9hm9272-!6%0ouz*r'
SECRET_KEY1 = '5pQsZXhU8vKyv7GxThldGn_JLK9UXVYyZD3GwQxsztY='
LOGOUT_REDIRECT_URL ='/Login'
LOGIN_REDIRECT_URL ='/Login'
LOGIN_URL="/library_list_login"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_COOKIE_AGE = 900  # 15 minutes idle timeout
SESSION_SAVE_EVERY_REQUEST = True
# Clickjacking Protection
X_FRAME_OPTIONS = 'DENY'

# Security Headers
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True


ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', 'oRVCHTumzesh-E71A-bAnjjEDuIlkceL6dvAYiCShp0=')

AUTH_USER_MODEL = 'Account.CustomUser'
# https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = True

# https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-DEFAULT_AUTO_FIELD
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Account Lockout 
AXES_FAILURE_LIMIT = 5  # Lock out after 5 failed login attempts
AXES_COOLOFF_TIME = 1
# Application definition

# APPS
# ------------------------------------------------------------------------------
DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    # "django.contrib.sites",
    'django.contrib.humanize',
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "django.contrib.humanize", # Handy template tags
    "django.contrib.admin",
    "django.forms",
    "django_user_agents"
]
THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
]

LOCAL_APPS = [
    "bootstrap.apps.apps.AppsConfig",
    "bootstrap.charts.apps.ChartsConfig",
    "bootstrap.crm.apps.CrmConfig",
    "bootstrap.dashboard.apps.DashboardConfig",
    "bootstrap.ecommerce.apps.EcommerceConfig",
    "bootstrap.extended.apps.ExtendedConfig",
    "bootstrap.form.apps.FormConfig",
    "bootstrap.icons.apps.IconsConfig",
    "bootstrap.layouts.apps.LayoutsConfig",
    "bootstrap.maps.apps.MapsConfig",
    "bootstrap.pages.apps.PagesConfig",
    "bootstrap.tables.apps.TablesConfig",
    "bootstrap.ui.apps.UiConfig",
    'axes',
    'corsheaders',
    'Account',
    'MenuManager',
    'Masters',
    'Reports',
    'administration',
    'L01',
    'L02',
    'library_reports',
    'book_report',
    'mini_system',
]

# Add 'storages' to THIRD_PARTY_APPS for all environments
# It won't cause issues if not configured
THIRD_PARTY_APPS.append('storages')

# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# SESSION_ENGINE ="django.contrib.sessions.backends.signed_cookies"
# SESSION_ENGINE ="django.contrib.sessions.backends.file"
# SESSION_FILE_PATH=r"D:\PYTHON PROJECTS\mantra_io"

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'middleware.no_cache.NoCacheMiddleware',
#     'middleware.session_security.SessionExpiryRedirectMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',  # MUST be first
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django_user_agents.middleware.UserAgentMiddleware',
#     # Your DB middleware should be **AFTER auth and messages**
#     'administration.middleware.LibraryDatabaseMiddleware',
#     'L01.middleware.MemberActivityMiddleware',
#     'Masters.middleware.VisitorTrackingMiddleware',
#     # Optional:
#     'django_auto_logout.middleware.auto_logout',
#     'axes.middleware.AxesMiddleware',
# ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'middleware.no_cache.NoCacheMiddleware',

    # ✅ Sessions MUST come first
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # ✅ Auth before anything that checks request.user
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # ✅ NOW your custom session logic
    'middleware.auth_flow.AuthFlowGuardMiddleware',
    'middleware.session_security.SessionExpiryRedirectMiddleware',
    'middleware.session_binding.SessionBindingMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',

    # App / DB / tracking middleware
    'administration.middleware.LibraryDatabaseMiddleware',
    'L01.middleware.MemberActivityMiddleware',
    'Masters.middleware.VisitorTrackingMiddleware',

    # Optional / security
    # 'django_auto_logout.middleware.auto_logout',  # recommended to REMOVE
    'axes.middleware.AxesMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://push3.aclgateway.com',
    'https://www.nmmclibrary.in',    # ← Add your domain
    'https://nmmclibrary.in',        # ← Add non-www version
]
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    'http://push3.aclgateway.com',
    'https://www.nmmclibrary.in',    # ← Add your domain
    'https://nmmclibrary.in',        # ← Add non-www version
]
AUTO_LOGOUT = {
    'IDLE_TIME': 900,
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
    'MESSAGE': 'The session has expired. Please login again to continue.',
}
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
   
]

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'WARNING',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),  # Changed to relative path
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'WARNING',
#             'propagate': True,
#         },
#     },
# }
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # Add any additional authentication backends if needed
    'axes.backends.AxesStandaloneBackend',  # Add this line
]

ROOT_URLCONF = 'NLMS.urls'
X_FRAME_OPTIONS = 'SAMEORIGIN'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": ['Template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
                'Account.context_processors.logged_in_user',
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
            ],
        },
    },
]

WSGI_APPLICATION = 'NLMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': { 'min_length': 8,},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

TIME_ZONE = 'Asia/Kolkata' 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# ========== AWS S3 CONFIGURATION (For Production) ==========
# ========== AWS S3 CONFIGURATION (For Production) ==========
if ENVIRONMENT == 'production':
    # AWS S3 Settings
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-south-1')
    
    if AWS_STORAGE_BUCKET_NAME:
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
        
        # S3 Settings for buckets with ACLs disabled (modern AWS)
        AWS_S3_FILE_OVERWRITE = False
        AWS_DEFAULT_ACL = None  # ← CHANGE FROM 'public-read' TO None
        AWS_QUERYSTRING_AUTH = False
        
        # Important: Don't set ACL for buckets with ACLs disabled
        AWS_S3_OBJECT_PARAMETERS = {
            'CacheControl': 'max-age=86400',
        }
        
        # ✅ Set the default storage
        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
        
        # ✅ S3 base path configuration
        S3_BASE_PATH = 'Documents/'  # This is what we need for production
        
        print(f"=== S3 Configuration Loaded ===")
        print(f"Bucket: {AWS_STORAGE_BUCKET_NAME}")
        print(f"Region: {AWS_S3_REGION_NAME}")
        print(f"S3 Base Path: '{S3_BASE_PATH}'")
        print(f"ACL Setting: None (bucket has ACLs disabled)")

# ========== FILE STORAGE BASE PATH ==========
# Set base path for file storage (empty for local/test, 'Documents/' for production)
if ENVIRONMENT != 'production':
    # For local and test environments - set empty base path
    S3_BASE_PATH = ''  # Empty string for local filesystem
    print(f"File Storage Base Path for {ENVIRONMENT}: '{S3_BASE_PATH}'")

# Make sure S3_BASE_PATH is defined for all environments
if 'S3_BASE_PATH' not in locals():
    S3_BASE_PATH = ''
    print(f"Default File Storage Base Path: '{S3_BASE_PATH}'")
    
# For production with domain (should be True when you have SSL certificate)
if ENVIRONMENT == 'production':
    SESSION_COOKIE_SECURE = True        # ← Set to False without SSL
    CSRF_COOKIE_SECURE = True           # ← Set to False without SSL
    SECURE_SSL_REDIRECT = True          # ← Set to False without SSL
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Keep SITE_URL as HTTP for now
    SITE_URL = "https://www.nmmclibrary.in"
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False