# Generated by Django 4.2.23 on 2026-02-09 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('theft', 'Theft Attempt'), ('test', 'Test Alarm'), ('system', 'System Error')], max_length=20)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_alarm_log',
            },
        ),
        migrations.CreateModel(
            name='ExitScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_rfid', models.CharField(max_length=50)),
                ('book_title', models.CharField(blank=True, max_length=200)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_authorized', models.BooleanField(default=False)),
                ('alarm_triggered', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tbl_exit_scan',
            },
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('book_rfid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_rfid', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='Test User', max_length=100)),
                ('book_title', models.CharField(default='Test Book', max_length=200)),
                ('issue_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_issued_book',
            },
        ),
    ]
