# Generated by Django 4.2.23 on 2026-02-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExitScan',
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
