# Generated by Django 4.2.23 on 2026-02-10 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0031_bookcatalog_author_fk_bookcatalog_author_short_name'),
        ('L01', '0060_memberentryexit_member'),
        ('mini_system', '0002_delete_exitscan_delete_issuedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('book_rfid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_rfid', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='Test User', max_length=100)),
                ('book_title', models.CharField(default='Test Book', max_length=200)),
                ('issue_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.bookcatalog')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L01.membershipdetails')),
            ],
            options={
                'db_table': 'tbl_issued_book',
            },
        ),
        migrations.CreateModel(
            name='ExitScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_rfid', models.CharField(max_length=50)),
                ('book_title', models.CharField(blank=True, max_length=200)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_authorized', models.BooleanField(default=False)),
                ('alarm_triggered', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.bookcatalog')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='L01.membershipdetails')),
            ],
            options={
                'db_table': 'tbl_exit_scan',
            },
        ),
    ]
