# Generated by Django 4.2.7 on 2025-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_librarymasterL02',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('library_code', models.TextField(blank=True, null=True)),
                ('library_name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('parent_ward', models.TextField(blank=True, null=True)),
                ('library_accounting_code', models.TextField(blank=True, null=True)),
                ('landing_page_link', models.TextField(blank=True, null=True)),
                ('about_library', models.TextField(blank=True, null=True)),
                ('library_rules', models.TextField(blank=True, null=True)),
                ('membership_rules', models.TextField(blank=True, null=True)),
                ('membership_page_link', models.TextField(blank=True, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('location_url', models.TextField(blank=True, null=True)),
                ('librarian_name', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('instagram_url', models.TextField(blank=True, null=True)),
                ('youtube_url', models.TextField(blank=True, null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_librarymasterL02',
            },
        ),
    ]
